FROM eclipse-temurin:17-jre-alpine

COPY target/github-portfolio-generator-jar-with-dependencies.jar /gpg.jar
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
